function [fitresult, gof] = createFit(x_data, y_data, z_data)
%CREATEFIT(X_DATA,Y_DATA,Z_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x_data
%      Y Input : y_data
%      Z Output: z_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Mar-2021 22:09:43


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x_data, y_data, z_data );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' , 'Visible', 'off');


h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'z_data vs. x_data, y_data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'BARE_p_value', 'Interpreter', 'none' );
ylabel( 'Zone1_conductivity', 'Interpreter', 'none' );
zlabel( 'Surface_potential(mV)', 'Interpreter', 'none' );
grid on


